name: Generate Docs

on:
  push:
    branches:
      - main
      - dev

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Generate HTML docs with Sphinx
        run: |
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
          sphinx-apidoc -o docs/source src/news_mcp_server
          make -C docs html

      - name: Upload docs artifact
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          name: api-docs
          path: docs 